---
title: "ProgramEvalPS3"
author: "Jessica Prus and Arianna Wooten"
date: "2026-05-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. In a fully ideal world, we would measure the impact of providing access to 
mobile banking on monthly household income using randomized control trials 
(RCTs). Two RCTs would occur: one measuring the impact on rural communities, and 
the other measuring the impact on peri-urban communities. To maximize the amount 
of data generated, each RCT would include all individuals in rural and peri-
urban communities. For each population (rural and peri-urban), the population 
would be divided into two comparable groups. One half of the population would 
be assigned a treatment status of receiving access to mobile banking, and the 
other half would serve as a comparative control group who does not receive 
access to mobile banking. The average treatment effect would be estimated by 
finding the difference in monthly household incomes between households who 
received access to mobile banking and those who did not. The relationship 
between household income and mobile banking access would further be estimated 
using a linear regression. This calculation would include controls for variables 
which have the potential to affect monthly household incomes in order to isolate 
the effect of mobile banking access on monthly household income.

2. First, I would use the household's pre-mobile banking trends to estimate what
the household's income would be without mobile banking at a given time *t*
after the introduction of mobile banking access. Next, I would compare that 
income estimate to the household's true income at time *t*. 

In math, I would run a regression of income on time: Y = m[time] + b
where Y is income, time spans from 2002 to 2008 (pre-treatment period), and
b is the y-intercept (income at t=0). The coefficient m would be the estimated
causal effect. 

The key assumption embedded in this approach are that there were no 
external factors/shocks that impacted income at the same time as mobile 
banking. An external shock such as a career change or promotion within the
household could significantly bias our estimate.

3. It would be better to have data on multiple households, especially data on 
all households that gained access in 2009, to confirm trends and ensure 
comparability. Comparability would confirm that the data from the single 
household is representative of the characteristics and patterns observed in 
other households that gained access. Adding more households would also increase 
the precision and decrease the bias of the estimated causal effect. Data on 
households that never registered for mobile banking would be useful as a 
counterfactual to the data from households who did. Non-registered households 
can only be used as a counterfactual with the assumptions that households that 
did not register are otherwise similar to those that did, and that any 
differences in income are due to their registration status. If these assumptions 
hold, then the data can be used to estimate the effects of mobile banking access 
on household income by finding the average difference in incomes between 
registered and non- registered households. The difference in incomes can be 
calculated by regressing mobile banking access on household income using a 
time-series difference-in-differences regression: 

estimated causal effect = alpha + tau(registration status * post-treatment 
incomes)it + beta(registration status)i + delta(post-treatment incomes)t + 
gamma(covariates)it + (error term)it

One concern in using this approach is that it is unable to control for 
unobserved characteristics. However, ensuring that  populations are comparable 
decreases the likelihood that unobserved characteristics bias the estimated 
causal effect.

4. I would utilize a time-series diff-in-diff approach, regressing income on 
time for two household groups: households that eventually got access to mobile
banking and households that did not. This would involve fixed effects methodology
to account for the varying treatment times.

In math: Yit = tau(Dit) + beta(Xit) + [error]
where Yit is the income for household i at time t, tau is the estimated treatment
effect, Dit is the treatment status for household i at time t, and Xit represents
covariates. 

The key assumption here is the parallel trends assumption; our estimate will 
only be unbiased if the timing of treatment was random and no external factors 
changed between the pre- and post-treatment periods, impacting our outcome variable.
We should be concerned that some households gained access to mobile banking 
because of income-related factors like increased wifi access or a newfound
ability to afford a cell phone. 

5.

6.

7.

8.

9.

10.



